name: Daily CI Report

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        continue-on-error: true   # Allow next steps to run
        run: npx playwright test --reporter=html

      - name: Ensure report exists
        if: always()
        run: |
          if [ ! -d "playwright-report" ]; then
            echo "No report found, creating dummy one..."
            mkdir playwright-report
            echo "<html><body><h1>No report generated</h1></body></html>" > playwright-report/index.html
          fi

      - name: Zip HTML report
        if: always()
        run: zip -r playwright-report.zip playwright-report

      - name: Create email body
        if: always()
        run: |
          RESULT="FAILED"
          if [ "${{ job.status }}" == "success" ]; then RESULT="PASSED"; fi
          cat << EOF > email_body.html
          <h2>Daily Playwright Test Report - ${RESULT}</h2>
          <p>The HTML test report is attached as a ZIP file.</p>
          <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View on GitHub</a></p>
          EOF

      - name: Send Email with Playwright HTML Report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily Playwright Test Report - ${{ github.run_id }}"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
          ignore_cert: true
          priority: normal
          body: file://email_body.html
          attachments: playwright-report.zip

      - name: Fail job if tests failed
        run: exit 1
        if: failure()  # Will fail job if earlier test step failed
