name: Daily CI Report

on:
  schedule:
    - cron: "0 5 * * *" # Runs daily at 05:00 UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=html
        continue-on-error: true # Prevents stopping on failure

      - name: Upload Playwright HTML report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report

      - name: Create email body
        if: always()
        run: |
          cat << 'EOF' > email_body.html
          <h2>Daily Playwright Test Report</h2>
          <p>Job Status: <b>${{ job.status }}</b></p>
          <p>The HTML report has been uploaded as an artifact.</p>
          <p>You can download it here:</p>
          <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">🔗 Click here to view & download the report</a></p>
          EOF

      - name: Send Email with Report Link
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Playwright Test Report - ${{ job.status }}"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
          body: file://email_body.html
