name: Daily CI Report

on:
  schedule:
    - cron: "0 5 * * *" # Runs daily at 05:00 UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04  # Pinned to avoid Ubuntu 24.04 dependency issues

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      - name: Zip HTML report
        run: zip -r playwright-report.zip playwright-report

      - name: Create email body
        run: |
          cat << 'EOF' > email_body.html
          <h2>Daily Playwright Test Report</h2>
          <p>The HTML test report is attached as a ZIP file.</p>
          <p>You can also view it from the GitHub Actions run:</p>
          <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">Click here to view</a></p>
          EOF

      - name: Send Email with Playwright HTML Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily Playwright Test Report - ${{ github.run_id }}"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: file://email_body.html
          attachments: playwright-report.zip
